title:              Testing Jekyll
email:              pi@mrow.dev
description:        "Testing Jekyll for a client's website"
author:             Pi
baseurl:            ""
url:                https://pithesnep.github.io

# Social Profiles
twitter_username:   PiTheSnep
github_username:    PiTheSnep
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   # UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
